---
- include_vars: "{{ ansible_distribution }}.yml"

- name: Add duplicity repository
  apt_repository:
    repo: ppa:duplicity-team/ppa
    state: present
    update_cache: yes
  when: backup_duplicity_ppa

- set_fact: 
    backup_duplicity_pkg: "{{ backup_duplicity_pkg }}={{ backup_duplicity_version }}"
  when: backup_duplicity_version

- name: Install duplicity
  apt:
    name: "{{ backup_duplicity_pkg }}"
    state: present

- name: Install core dependencies
  apt:
    name:
      - cron
      - gzip
      - duply
    state: present
